# Generated by Django 5.2.11 on 2026-02-27 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('daily_target_mins', models.IntegerField(default=30)),
                ('daily_target_calories', models.IntegerField(default=300)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('completion_status', models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='core.user')),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.user')),
            ],
            options={
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('requester', 'receiver'), name='unique_friendship')],
            },
        ),
    ]
