# Generated by Django 5.2.12 on 2026-03-17 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('badge_type', models.CharField(choices=[('calories', 'Calories Burned'), ('distance', 'Distance Covered'), ('sessions', 'Sessions Completed'), ('streak', 'Streak'), ('jumps', 'Total Jumps'), ('crouches', 'Total Crouches')], max_length=50)),
                ('target_value', models.FloatField()),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['badge_type', 'target_value'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='daily_target_mins',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='average_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='character_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='distance_covered',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_crouches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_jumps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_target_distance',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_calories', models.IntegerField(default=0)),
                ('total_duration_mins', models.IntegerField(default=0)),
                ('target_met', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='core.user')),
            ],
            options={
                'db_table': 'daily_progress',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_progress')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_progress', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='core.user')),
            ],
            options={
                'db_table': 'user_badges',
                'ordering': ['-is_completed', 'badge__badge_type', 'badge__target_value'],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge')],
            },
        ),
    ]
