# Generated by Django 5.2.12 on 2026-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schema_v2_distance_streaks_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='total_left_leans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_right_leans',
            field=models.IntegerField(default=0),
        ),
    ]
